mongodb:
  auth:
    passwords:
      - rocketchat
    rootPassword: rocketchatroot
  mongodbUri: mongodb://admin:2nJami9FzOD4ocod@cluster0.iws1lhb.mongodb.net/test
rocketchat:
  externalDatabase:
    enabled: true
    mongodbUri: "{{ .Values.mongodb.mongodbUri }}"