mongodb:
  auth:
    passwords:
      - rocketchat
    rootPassword: rocketchatroot
  mongodbUri: mongodb://admin:qut0HHdryUdwL75a@cluster0.iws1lhb.mongodb.net/test
rocketchat:
  externalDatabase:
    enabled: true
    mongodbUri: "{{ .Values.mongodb.mongodbUri }}"